# Generated by Django 5.0.7 on 2024-07-27 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discussions", "0001_initial"),
        ("users", "0002_rename_user_spyneuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussion",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="static/images/"),
        ),
        migrations.AlterField(
            model_name="discussion",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.spyneuser",
            ),
        ),
    ]
